[package]
name = "test-support"
version.workspace = true
edition = "2021"
publish = false

[dependencies]
fastrand = "2.3.0"
time = "0.3.47"
trillium = "0.2.20"
trillium-macros = "0.0.6"
trillium-testing = { version = "0.7.0", features = ["tokio"] }
divviup-api.workspace = true
serde = "1.0.228"
serde_json = "1.0.149"
thiserror = "2.0.18"
tracing = "0.1.44"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.22", features = [
        "json",
        "env-filter",
        "std",
        "fmt",
] }
trillium-client = { version = "0.6.2", features = ["json"] }
trillium-http = "0.3.14"
trillium-rustls = "0.8.1"
trillium-tokio = "0.4.0"
url = "2.5.8"
uuid = { version = "1.20.0", features = ["v4", "fast-rng", "serde"] }
sea-orm = { version = "1.1.19", features = ["sqlx-sqlite"] }
pretty_assertions = "1.4.1"
rand = "0.8.5"
base64 = "0.22.1"
querystrong = "0.3.0"
test-harness = "0.3.1"
